---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Design/EvalExpression:
        enabled: false
    exclude_patterns:
    - "src/JsPhpize/Stream/"
  phpcodesniffer:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
