---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        exclude_paths:
        - "src/JsPhpize/Stream/ExpressionStream.php"
ratings:
  paths:
  - "**.php"
