---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Design/EvalExpression:
        enabled: false
    exclude_paths:
    - "src/JsPhpize/Stream/"
ratings:
  paths:
  - "**.php"
