language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

dist: trusty

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - echo "hhvm.php7.all=1" >> /tmp/hhvm.php.ini
  - phpenv config-add /tmp/hhvm.php.ini

before_script:
  - travis_retry composer self-update
  - if [[ `php -v | grep -c "HipHop"` > 0 ]]; then composer require phpunit/phpunit:^5.0 --no-update; fi;
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 58bc0544337c5270ef20d7ad2ab47df91f67bc66147c53ccbb84b6faf9ff1dbe
